name = "espresso-network"
version = "20250428-dev-node-decaf-pos"
description = "Espresso Network"

[var.Settings]
espTokenOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
espTokenInitialGrantRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
feeContractMultiSig = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
lightClientGenesisStateViewNum = "<%= toHex(0) %>"
lightClientGenesisStateBlockHeight = "<%= toHex(0) %>"
lightClientGenesisStateBlockCommRoot = "<%= toHex(0) %>"
lightClientGenesisStakeThreshold = "<%= toHex(1) %>"
lightClientGenesisStakeBlsKeyComm = "<%= toHex(6404508828895255916893827506275841427382744721239775140745462753544601985440n) %>"
lightClientGenesisStakeSchnorrKeyComm = "<%= toHex(1280444752930177982791997254719680985905658247245505815722065969671227685044n) %>"
lightClientGenesisStakeAmountComm = "<%= toHex(20800575916199869666564862039153542082238860599565034691999240975959073142491n) %>"
lightClientStateHistoryRetentionPeriod = "<%= toHex(60*60*24*10) %>"
lightClientOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[deploy.PlonkVerifier]
artifact = "PlonkVerifier"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.PlonkVerifierV2]
artifact = "PlonkVerifierV2"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.FeeContract]
artifact = "FeeContract"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.EspToken]
artifact = "EspToken"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.StakeTable]
artifact = "StakeTable"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.LightClient]
artifact = "LightClientMock"
libraries.PlonkVerifier = "<%= contracts.PlonkVerifier.address %>"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.LightClientV2]
artifact = "LightClientV2Mock"
libraries.PlonkVerifierV2 = "<%= contracts.PlonkVerifierV2.address %>"
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"

[deploy.EspTokenProxy]
artifact = "contracts/src/libraries/ERC1967Proxy.sol:ERC1967Proxy"
args = [
    "<%= contracts.EspToken.address %>",
    "<%= concat([toFunctionSelector('initialize(address,address)'), pad(settings.espTokenOwner), pad(settings.espTokenInitialGrantRecipient)]) %>",
]
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
depends = ["deploy.EspToken"]

[deploy.FeeContractProxy]
artifact = "contracts/src/libraries/ERC1967Proxy.sol:ERC1967Proxy"
args = [
    "<%= contracts.FeeContract.address %>",
    "<%= concat([toFunctionSelector('initialize(address)'), pad(settings.feeContractMultiSig)]) %>",
]
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
depends = ["deploy.FeeContract"]

[deploy.LightClientProxy]
artifact = "contracts/src/libraries/ERC1967Proxy.sol:ERC1967Proxy"
args= [
    "<%= contracts.LightClient.address %>",
    "<%= concat([toFunctionSelector('initialize((uint64,uint64,uint256),(uint256,uint256,uint256,uint256),uint32,address)'), pad(settings.lightClientGenesisStateViewNum), pad(settings.lightClientGenesisStateBlockHeight), pad(settings.lightClientGenesisStateBlockCommRoot), pad(settings.lightClientGenesisStakeThreshold), pad(settings.lightClientGenesisStakeBlsKeyComm), pad(settings.lightClientGenesisStakeSchnorrKeyComm), pad(settings.lightClientGenesisStakeAmountComm), pad(settings.lightClientStateHistoryRetentionPeriod), pad(settings.lightClientOwner)]) %>",
]
create2 = true
salt = "<%= zeroHash %>"
ifExists = "continue"
depends = ["deploy.LightClient"]
